apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: two-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: vishalsaxena29/frontend-app:replaceImageTag
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://api.default.svc.cluster.local/api/tasks"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: two-tier
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: ClusterIP
  selector:
    role: frontend        
